// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "forge-std/console.sol";

// AUTO-GENERATED by DelegateGuard harness generator
// Bug class : DC-01 — Storage collision on re-delegation
// Contract  : {contract_name}
// Source    : {source_file}:{line}
// Run with  : forge test --match-contract {test_contract_name} -vv

// ── paste your delegate contracts here ──────────────────────────────────────

interface IVulnDelegate {{
    function initialize(address owner) external;
    // TODO: add other functions from {contract_name}
}}

interface ISecondDelegate {{
    function initialize(address guardian, uint256 delay) external;
    // TODO: add functions from your second delegate
}}

// ────────────────────────────────────────────────────────────────────────────

contract {test_contract_name} is Test {{

    // Simulated EOA — replace with actual addresses if testing on fork
    address payable public victimEOA;
    address public owner     = makeAddr("owner");
    address public guardian  = makeAddr("guardian");

    // Deploy your actual delegate contracts here
    // IVulnDelegate public delegateA;
    // ISecondDelegate public delegateB;

    function setUp() public {{
        victimEOA = payable(makeAddr("victimEOA"));
        vm.deal(victimEOA, 5 ether);

        // TODO: deploy delegate contracts
        // delegateA = IVulnDelegate(address(new YourDelegateA()));
        // delegateB = ISecondDelegate(address(new YourDelegateB()));
    }}

    // ── RED: proves storage collision ────────────────────────────────────────

    function test_DC01_StorageCorruptedAfterReDelegation() public {{
        // Step 1: delegate to A, initialize
        // _etch7702(victimEOA, address(delegateA));
        // vm.prank(owner);
        // IVulnDelegate(victimEOA).initialize(owner);

        // Capture slot 0 before re-delegation
        bytes32 slotBefore = vm.load(victimEOA, bytes32(uint256(0)));
        console.log("Slot 0 before re-delegation:");
        console.logBytes32(slotBefore);

        // Step 2: re-delegate to B, overwrite slot 0
        // _etch7702(victimEOA, address(delegateB));
        // vm.store(victimEOA, bytes32(uint256(0)), bytes32(uint256(uint160(guardian))));

        // Step 3: switch back to A — slot 0 is now corrupted
        // _etch7702(victimEOA, address(delegateA));
        bytes32 slotAfter = vm.load(victimEOA, bytes32(uint256(0)));
        console.log("Slot 0 after re-delegation (should differ):");
        console.logBytes32(slotAfter);

        // INVARIANT: slot 0 must not change after re-delegation
        // This assertion FAILS on vulnerable contracts
        assertEq(slotBefore, slotAfter, "COLLISION: storage corrupted by re-delegation");
    }}

    // ── GREEN: proves ERC-7201 fix ───────────────────────────────────────────

    function test_DC01_ERC7201_NoCollision() public {{
        // TODO: repeat above test with namespaced-storage delegates
        // assert slots diverge and owner/guardian remain independent
        assertTrue(true, "placeholder — implement with fixed contracts");
    }}

    // ── Helpers ──────────────────────────────────────────────────────────────

    function _etch7702(address eoa, address delegate) internal {{
        vm.etch(eoa, delegate.code);
    }}
}}
