// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "forge-std/console.sol";

// AUTO-GENERATED by DelegateGuard harness generator
// Bug class : DC-02 — Unprotected / front-runnable initializer
// Contract  : {contract_name}
// Function  : {function_name}
// Source    : {source_file}:{line}
// Run with  : forge test --match-contract {test_contract_name} -vv

interface IVulnDelegate {{
    function {function_name}(address owner) external;
    // TODO: add functions from {contract_name}
}}

contract {test_contract_name} is Test {{

    address payable public victimEOA;
    address public attacker = makeAddr("attacker");
    address public victim;

    function setUp() public {{
        victim    = makeAddr("victim");
        victimEOA = payable(victim);
        vm.deal(victimEOA, 5 ether);

        // TODO: deploy {contract_name}
        // IVulnDelegate delegate = new {contract_name}();
        // _etch7702(victimEOA, address(delegate));
    }}

    // ── RED: proves front-run ────────────────────────────────────────────────

    function test_DC02_AttackerFrontRunsInitializer() public {{
        // Attacker calls initialize() before victim — no auth check stops them
        vm.prank(attacker);
        // IVulnDelegate(victimEOA).{function_name}(attacker);

        // INVARIANT: only the EOA itself should be able to initialize
        // bytes32 ownerSlot = vm.load(victimEOA, bytes32(uint256(0)));
        // address storedOwner = address(uint160(uint256(ownerSlot)));
        // assertEq(storedOwner, attacker, "FRONT-RUN: attacker became owner");
        // assertNotEq(storedOwner, victim, "victim is NOT the owner");

        console.log("Attacker address:", attacker);
        console.log("Victim address:  ", victim);
        // console.log("Stored owner:    ", storedOwner);
        assertTrue(true, "TODO: uncomment assertions above");
    }}

    // ── RED: victim cannot re-initialize after front-run ────────────────────

    function test_DC02_VictimLockedOut() public {{
        vm.prank(attacker);
        // IVulnDelegate(victimEOA).{function_name}(attacker);

        vm.prank(victim);
        vm.expectRevert(); // "already initialized" or equivalent
        // IVulnDelegate(victimEOA).{function_name}(victim);
        assertTrue(true, "TODO: uncomment assertions above");
    }}

    // ── GREEN: self-auth initializer blocks front-run ────────────────────────

    function test_DC02_SelfAuthBlocksFrontRun() public {{
        // TODO: deploy fixed delegate and verify attacker is blocked
        vm.startPrank(attacker, attacker); // attacker is both msg.sender and tx.origin
        vm.expectRevert(); // "only EOA can initialize itself"
        // IFixedDelegate(victimEOA).{function_name}(attacker);
        vm.stopPrank();
        assertTrue(true, "TODO: uncomment assertions above");
    }}

    function _etch7702(address eoa, address delegate) internal {{
        vm.etch(eoa, delegate.code);
    }}
}}
