// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "forge-std/console.sol";

// AUTO-GENERATED by DelegateGuard harness generator
// Bug class : DC-04 — Missing per-call authentication
// Contract  : {contract_name}
// Function  : {function_name}
// Source    : {source_file}:{line}
// Run with  : forge test --match-contract {test_contract_name} -vv

interface IVulnDelegate {
    function {function_name}(address payable to, uint256 amount) external;
    // TODO: add all unprotected functions from {contract_name}
}

contract {test_contract_name} is Test {

    address payable public victimEOA;
    address public attacker = makeAddr("attacker");
    address public victim   = makeAddr("victim");

    function setUp() public {
        victimEOA = payable(victim);
        vm.deal(victimEOA, 5 ether);

        // TODO: deploy and etch {contract_name}
        // IVulnDelegate delegate = new {contract_name}();
        // _etch7702(victimEOA, address(delegate));
        // vm.prank(victim); IVulnDelegate(victimEOA).initialize(victim, makeAddr("fee"));
    }

    // ── RED: anyone can call the unprotected function ────────────────────────

    function test_DC04_AnyoneCanCall_{function_name}() public {
        uint256 balanceBefore = victimEOA.balance;

        // Attacker calls without being the owner — no auth check stops them
        vm.prank(attacker);
        // IVulnDelegate(victimEOA).{function_name}(payable(attacker), victimEOA.balance);

        // INVARIANT: only owner should be able to call this function
        // assertEq(victimEOA.balance, 0, "MISSING AUTH: attacker drained EOA");
        // assertGt(attacker.balance, 0, "attacker profited");
        console.log("Victim balance before:", balanceBefore);
        // console.log("Victim balance after: ", victimEOA.balance);
        assertTrue(true, "TODO: uncomment assertions");
    }

    // ── GREEN: onlyOwner blocks attacker ────────────────────────────────────

    function test_DC04_OnlyOwnerCanCall_{function_name}() public {
        // TODO: deploy fixed delegate with onlyOwner modifier
        vm.prank(attacker);
        vm.expectRevert(); // "not owner" or equivalent
        // IFixedDelegate(victimEOA).{function_name}(payable(attacker), 1 ether);
        assertTrue(true, "TODO: uncomment assertions");
    }

    function _etch7702(address eoa, address delegate) internal {
        vm.etch(eoa, delegate.code);
    }
}
