// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "forge-std/console.sol";

// AUTO-GENERATED by DelegateGuard harness generator
// Bug class : DC-05 — Unsafe inner DELEGATECALL
// Contract  : {contract_name}
// Function  : {function_name}
// Source    : {source_file}:{line}
// Run with  : forge test --match-contract {test_contract_name} -vv

// Malicious plugin: drains ETH when delegatecalled
contract MaliciousPlugin_{test_contract_name} {
    function drain(address payable attacker) external {
        (bool ok,) = attacker.call{value: address(this).balance}("");
        require(ok, "drain failed");
    }
}

interface IVulnDelegate {
    function {function_name}(address plugin, bytes calldata data) external returns (bytes memory);
}

contract {test_contract_name} is Test {

    address payable public victimEOA;
    address public attacker = makeAddr("attacker");
    MaliciousPlugin_{test_contract_name} public malPlugin;

    function setUp() public {
        victimEOA = payable(makeAddr("victimEOA"));
        vm.deal(victimEOA, 5 ether);
        malPlugin = new MaliciousPlugin_{test_contract_name}();

        // TODO: deploy and etch {contract_name}
        // _etch7702(victimEOA, address(new {contract_name}()));
        // vm.prank(victimEOA); IVulnDelegate(victimEOA).initialize(victimEOA);
    }

    // ── RED: malicious plugin drains EOA ─────────────────────────────────────

    function test_DC05_MaliciousPluginDrainsETH() public {
        uint256 balanceBefore = victimEOA.balance;

        // Attacker tricks owner into calling executePlugin with malPlugin
        // (or uses the unauthenticated delegateTo path directly)
        vm.prank(attacker);
        // IVulnDelegate(victimEOA).{function_name}(
        //     address(malPlugin),
        //     abi.encodeWithSelector(MaliciousPlugin_{test_contract_name}.drain.selector, attacker)
        // );

        // INVARIANT: arbitrary plugin should not be callable
        // assertEq(victimEOA.balance, 0, "INNER DELEGATECALL: EOA drained");
        console.log("Victim balance before:", balanceBefore);
        assertTrue(true, "TODO: uncomment assertions");
    }

    // ── GREEN: allowlist blocks malicious plugin ─────────────────────────────

    function test_DC05_AllowlistBlocksMaliciousPlugin() public {
        // TODO: deploy fixed delegate, verify malPlugin is rejected
        vm.expectRevert(); // "plugin not allowed"
        // IFixedDelegate(victimEOA).{function_name}(address(malPlugin), "");
        assertTrue(true, "TODO: uncomment assertions");
    }

    function _etch7702(address eoa, address delegate) internal {
        vm.etch(eoa, delegate.code);
    }
}
