// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "forge-std/console.sol";

// AUTO-GENERATED by DelegateGuard harness generator
// Bug class : DC-08 — Signature malleability
// Contract  : {contract_name}
// Source    : {source_file}:{line}
// Run with  : forge test --match-contract {test_contract_name} -vv

contract {test_contract_name} is Test {

    address payable public victimEOA;
    uint256 public victimKey = 0xC0FFEE;
    address public attacker  = makeAddr("attacker");
    address payable public recipient = payable(makeAddr("recipient"));

    // secp256k1 curve order
    uint256 constant SECP256K1_N =
        0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141;

    function setUp() public {
        victimEOA = payable(vm.addr(victimKey));
        vm.deal(victimEOA, 10 ether);

        // TODO: deploy and etch {contract_name}
        // _etch7702(victimEOA, address(new {contract_name}()));
        // vm.prank(victimEOA); {contract_name}(victimEOA).initialize(victimEOA);
    }

    // ── RED: malleable signature bypasses used-sig check ────────────────────

    function test_DC08_MalleableSigBypassesReplayProtection() public {
        // Step 1: build and sign a withdraw message
        // bytes32 digest = _buildDigest(recipient, 1 ether);
        // (uint8 v, bytes32 r, bytes32 s) = vm.sign(victimKey, digest);
        // bytes memory originalSig = abi.encodePacked(r, s, v);

        // Step 2: execute with original sig (marks it as used)
        // {contract_name}(victimEOA).withdraw(recipient, 1 ether, originalSig);
        // assertEq(recipient.balance, 1 ether);

        // Step 3: compute malleable form (v', r, n-s)
        // uint8 mallV = v == 27 ? 28 : 27;
        // bytes32 mallS = bytes32(SECP256K1_N - uint256(s));
        // bytes memory malleableSig = abi.encodePacked(r, mallS, mallV);

        // Step 4: replay with malleable form — should FAIL but doesn't
        vm.prank(attacker);
        // {contract_name}(victimEOA).withdraw(recipient, 1 ether, malleableSig);
        // assertEq(recipient.balance, 2 ether, "REPLAY: 2 ETH from one signing");

        assertTrue(true, "TODO: implement digest builder for {contract_name}");
    }

    // ── GREEN: lower-s enforcement blocks malleable replay ───────────────────

    function test_DC08_HighSRejectedByFixedDelegate() public {
        // TODO: deploy fixed delegate, verify high-s sig reverts
        vm.expectRevert(); // "high-s rejected"
        assertTrue(true, "TODO: implement");
    }

    function _sign(uint256 key, bytes32 digest) internal pure returns (bytes memory) {
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(key, digest);
        return abi.encodePacked(r, s, v);
    }

    function _etch7702(address eoa, address delegate) internal {
        vm.etch(eoa, delegate.code);
    }
}
