// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";

// AUTO-GENERATED by DelegateGuard harness generator
// Bug class : PA-02 — msg.sender == tx.origin EOA gate
// Contract  : {contract_name}
// Function  : {function_name}
// Source    : {source_file}:{line}

interface IVulnProtocol {
    function {function_name}() external;
    function hasClaimed(address) external view returns (bool);
}

contract {test_contract_name} is Test {

    address public delegatedEOA = makeAddr("delegatedEOA");
    address public delegate;

    function setUp() public {
        // TODO: deploy a dummy delegate and etch it
        // delegate = address(new DummyDelegate());
        // vm.etch(delegatedEOA, delegate.code);

        // TODO: deploy {contract_name}
        // IVulnProtocol protocol = new {contract_name}();
    }

    // ── RED: delegated EOA passes the EOA gate ────────────────────────────────

    function test_PA02_DelegatedEOAPassesGate() public {
        // Delegated EOA sends its own tx: msg.sender == tx.origin == delegatedEOA
        vm.startPrank(delegatedEOA, delegatedEOA);
        // IVulnProtocol(address(protocol)).{function_name}();
        vm.stopPrank();

        // INVARIANT: delegated EOA (which has code) should NOT pass an EOA gate
        // assertTrue(protocol.hasClaimed(delegatedEOA), "GATE BYPASSED: delegated EOA claimed");
        assertTrue(true, "TODO: uncomment assertions");
    }

    // ── GREEN: allowlist correctly gates access ───────────────────────────────

    function test_PA02_AllowlistBlocksUnlistedAddress() public {
        // TODO: deploy fixed contract with Merkle allowlist
        // bytes32[] memory emptyProof = new bytes32[](0);
        // vm.expectRevert("not in allowlist");
        // IFixedProtocol(address(fixed)).claimWithProof(emptyProof);
        assertTrue(true, "TODO: implement");
    }
}
