// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";

// AUTO-GENERATED by DelegateGuard harness generator
// Bug class : PA-03 — extcodesize == 0 EOA check
// Contract  : {contract_name}
// Function  : {function_name}
// Source    : {source_file}:{line}

contract {test_contract_name} is Test {

    address payable public delegatedEOA;
    address public dummyDelegate;

    function setUp() public {
        delegatedEOA  = payable(makeAddr("delegatedEOA"));
        dummyDelegate = address(new DummyDelegate_{test_contract_name}());
        vm.deal(delegatedEOA, 5 ether);

        // Simulate 7702: etch delegate code onto EOA
        vm.etch(delegatedEOA, dummyDelegate.code);

        // TODO: deploy {contract_name}
    }

    // ── RED: delegated EOA blocked by extcodesize check ──────────────────────

    function test_PA03_DelegatedEOABlocked() public {
        uint256 codeSize;
        assembly { codeSize := extcodesize(sload(delegatedEOA.slot)) }

        // Delegated EOA has extcodesize > 0 — breaks the check
        // vm.prank(delegatedEOA);
        // vm.expectRevert("only EOAs can deposit");
        // {contract_name}(protocol).{function_name}{value: 1 ether}();

        assertTrue(true, "TODO: uncomment assertions");
    }

    // ── GREEN: universal guard works for all callers ─────────────────────────

    function test_PA03_UniversalGuardAcceptsDelegatedEOA() public {
        // TODO: deploy fixed protocol and verify delegated EOA can interact
        assertTrue(true, "TODO: implement");
    }
}

contract DummyDelegate_{test_contract_name} {
    receive() external payable {}
}
