// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "forge-std/console.sol";

// AUTO-GENERATED by DelegateGuard harness generator
// Bug class : PA-05 — EOA = unique human assumption
// Contract  : {contract_name}
// Function  : {function_name}
// Source    : {source_file}:{line}

interface IVulnProtocol {
    function {function_name}() external;
    function hasClaimed(address) external view returns (bool);
}

contract {test_contract_name} is Test {

    address[] public farm; // EOA farm
    uint256 constant FARM_SIZE = 5;

    function setUp() public {
        // Generate EOA farm — in real attack these are generated from a BIP-39 seed
        for (uint256 i = 0; i < FARM_SIZE; i++) {
            farm.push(vm.addr(uint256(keccak256(abi.encode("farm", i)))));
        }
        // TODO: deploy {contract_name}
    }

    // ── RED: EOA farm claims multiple times ───────────────────────────────────

    function test_PA05_EOAFarmClaimsMultipleTimes() public {
        uint256 claimCount = 0;
        for (uint256 i = 0; i < farm.length; i++) {
            // Each EOA satisfies msg.sender == tx.origin
            vm.startPrank(farm[i], farm[i]);
            // IVulnProtocol(protocol).{function_name}();
            vm.stopPrank();
            claimCount++;
        }

        // INVARIANT: each address should claim at most once
        // but the farm claims FARM_SIZE times
        console.log("Farm claimed", claimCount, "times");
        // assertEq(claimCount, FARM_SIZE, "SYBIL: EOA farm claimed multiple times");
        assertTrue(true, "TODO: uncomment assertions");
    }

    // ── GREEN: Merkle allowlist blocks farm ───────────────────────────────────

    function test_PA05_AllowlistBlocksEOAFarm() public {
        bytes32[] memory emptyProof = new bytes32[](0);
        uint256 blockedCount = 0;

        for (uint256 i = 0; i < farm.length; i++) {
            vm.prank(farm[i]);
            try IVulnProtocol(address(0)).{function_name}() {
                // should not succeed
            } catch {
                blockedCount++;
            }
        }

        // assertEq(blockedCount, FARM_SIZE, "All farm EOAs blocked");
        assertTrue(true, "TODO: implement with fixed contract");
    }
}
