// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "forge-std/console.sol";

// AUTO-GENERATED by DelegateGuard harness generator
// Bug class : DC-03 — Cross-chain replay via chain_id = 0
// Contract  : DC03_CrossChainDelegate
// Source    : src/vulnerable/DC03_CrossChainDelegate.sol:20
// Run with  : forge test --match-contract DC03_DC03_CrossChainDelegate_Harness -vv

contract DC03_DC03_CrossChainDelegate_Harness is Test {

    address payable public victimEOA;
    uint256 public victimKey = 0xA11CE;
    address public attacker  = makeAddr("attacker");
    address public recipient = makeAddr("recipient");

    uint256 constant MAINNET_CHAIN_ID  = 1;
    uint256 constant ARBITRUM_CHAIN_ID = 42161;

    function setUp() public {
        victimEOA = payable(vm.addr(victimKey));
        vm.deal(victimEOA, 10 ether);

        // TODO: deploy DC03_CrossChainDelegate
        // DC03_CrossChainDelegate delegate = new DC03_CrossChainDelegate();
        // _etch7702(victimEOA, address(delegate));
        // vm.prank(victimEOA); DC03_CrossChainDelegate(victimEOA).initialize(victimEOA);
    }

    // ── RED: proves cross-chain replay ───────────────────────────────────────

    function test_DC03_MainnetSigReplayedOnArbitrum() public {
        // Step 1: victim signs on mainnet
        vm.chainId(MAINNET_CHAIN_ID);
        // bytes32 digest = _buildDigest(recipient, 1 ether, 0);
        // bytes memory sig = _sign(victimKey, digest);
        // Execute on mainnet...

        // Step 2: re-fund and switch to Arbitrum
        vm.deal(victimEOA, 10 ether);
        vm.chainId(ARBITRUM_CHAIN_ID);

        // INVARIANT: mainnet sig must NOT work on Arbitrum
        // vm.expectRevert("invalid signature");
        // DC03_CrossChainDelegate(victimEOA).executeBatch(..., sig);
        console.log("TODO: implement digest builder matching DC03_CrossChainDelegate");
        assertTrue(true, "placeholder");
    }

    // ── RED: domain separators identical across chains ───────────────────────

    function test_DC03_DomainSeparatorChainAgnostic() public {
        // _etch7702(victimEOA, address(new DC03_CrossChainDelegate()));
        vm.chainId(MAINNET_CHAIN_ID);
        // bytes32 domainA = DC03_CrossChainDelegate(victimEOA).domainSeparator();
        vm.chainId(ARBITRUM_CHAIN_ID);
        // bytes32 domainB = DC03_CrossChainDelegate(victimEOA).domainSeparator();
        // assertEq(domainA, domainB, "VULN: domain separator is chain-agnostic");
        assertTrue(true, "placeholder");
    }

    // ── GREEN: chain-bound domain separator blocks replay ────────────────────

    function test_DC03_FixedDomainDiffersPerChain() public {
        // TODO: deploy fixed version and verify domain separators differ
        assertTrue(true, "placeholder");
    }

    function _sign(uint256 key, bytes32 digest) internal pure returns (bytes memory) {
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(key, digest);
        return abi.encodePacked(r, s, v);
    }

    function _etch7702(address eoa, address delegate) internal {
        vm.etch(eoa, delegate.code);
    }
}
