// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "forge-std/console.sol";

// AUTO-GENERATED by DelegateGuard harness generator
// Bug class : DC-06 — Batch executor replay / nonce gaps
// Contract  : DC07_SweeperDelegate
// Function  : execute
// Source    : src/vulnerable/DC07_SweeperDelegate.sol:26
// Run with  : forge test --match-contract DC06_DC07_SweeperDelegate_execute_Harness -vv

contract DC06_DC07_SweeperDelegate_execute_Harness is Test {

    address payable public victimEOA;
    uint256 public victimKey = 0xB0B;
    address public attacker  = makeAddr("attacker");
    address payable public tokenA = payable(makeAddr("tokenA"));
    address payable public tokenB = payable(makeAddr("tokenB"));

    function setUp() public {
        victimEOA = payable(vm.addr(victimKey));
        vm.deal(victimEOA, 10 ether);

        // TODO: deploy and etch DC07_SweeperDelegate
        // _etch7702(victimEOA, address(new DC07_SweeperDelegate()));
        // vm.prank(victimEOA); DC07_SweeperDelegate(victimEOA).initialize(victimEOA);
    }

    // ── RED: per-target nonce replay ─────────────────────────────────────────

    function test_DC06_SameSignatureReplayedAgainstSecondTarget() public {
        // Sign a call to tokenA with nonce=0
        // bytes32 digest = _buildDigest(tokenA, "", 1 ether, 0);
        // bytes memory sig = _sign(victimKey, digest);

        // Execute against tokenA (legitimate)
        // DC07_SweeperDelegate(victimEOA).execute(tokenA, "", 1 ether, 0, sig);

        // REPLAY against tokenB (nonce=0 per-target, same sig works)
        vm.prank(attacker);
        // DC07_SweeperDelegate(victimEOA).execute(tokenB, "", 1 ether, 0, sig);

        // INVARIANT: same signature must not work against a second target
        // assertEq(tokenB.balance, 0, "REPLAY: signature worked against tokenB");
        assertTrue(true, "TODO: implement digest builder for DC07_SweeperDelegate");
    }

    // ── RED: no deadline — signature valid forever ───────────────────────────

    function test_DC06_OldSignatureStillValid() public {
        // bytes32 digest = _buildDigest(attacker, "", 1 ether, 0);
        // bytes memory sig = _sign(victimKey, digest);
        vm.warp(block.timestamp + 365 days);
        // Should revert if deadline enforced — doesn't on vulnerable contract
        // DC07_SweeperDelegate(victimEOA).execute(attacker, "", 1 ether, 0, sig);
        // assertEq(attacker.balance, 1 ether, "NO DEADLINE: 1-year-old sig worked");
        assertTrue(true, "TODO: implement digest builder");
    }

    // ── GREEN: global nonce + deadline block replays ─────────────────────────

    function test_DC06_GlobalNonceBlocksReplay() public {
        // TODO: implement with fixed contract
        assertTrue(true, "placeholder");
    }

    function _sign(uint256 key, bytes32 digest) internal pure returns (bytes memory) {
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(key, digest);
        return abi.encodePacked(r, s, v);
    }

    function _etch7702(address eoa, address delegate) internal {
        vm.etch(eoa, delegate.code);
    }
}
