// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "forge-std/console.sol";

// AUTO-GENERATED by DelegateGuard harness generator
// Bug class : DC-07 — Sweeper pattern
// Contract  : DC04_NoAuthDelegate
// Function  : transferETH
// Source    : src/vulnerable/DC04_NoAuthDelegate.sol:47
// Run with  : forge test --match-contract DC07_DC04_NoAuthDelegate_transferETH_Harness -vv

interface ISweeper {
    function transferETH(address target, bytes calldata data) external payable returns (bool, bytes memory);
    function sweepETH(address payable target) external;
}

contract DC07_DC04_NoAuthDelegate_transferETH_Harness is Test {

    address payable public victimEOA;
    address public attacker = makeAddr("attacker");

    function setUp() public {
        victimEOA = payable(makeAddr("victimEOA"));
        vm.deal(victimEOA, 10 ether);

        // TODO: deploy and etch DC04_NoAuthDelegate
        // ISweeper delegate = ISweeper(address(new DC04_NoAuthDelegate()));
        // _etch7702(victimEOA, address(delegate));
    }

    // ── RED: attacker sweeps all ETH ─────────────────────────────────────────

    function test_DC07_AttackerSweepsETH() public {
        uint256 balanceBefore = victimEOA.balance;

        vm.prank(attacker);
        // ISweeper(victimEOA).sweepETH(payable(attacker));

        // INVARIANT: unauthorized callers must not be able to drain ETH
        // assertEq(victimEOA.balance, 0, "SWEEPER: victim fully drained");
        // assertEq(attacker.balance, balanceBefore, "attacker received victim ETH");
        console.log("Victim balance before:", balanceBefore / 1e18, "ETH");
        assertTrue(true, "TODO: uncomment assertions");
    }

    // ── RED: attacker uses execute() with arbitrary calldata ─────────────────

    function test_DC07_ArbitraryCallDrainsEOA() public {
        vm.prank(attacker);
        // ISweeper(victimEOA).transferETH(attacker, "");
        // assertEq(victimEOA.balance, 0);
        assertTrue(true, "TODO: implement");
    }

    // ── GREEN: auth + allowlist blocks the sweep ─────────────────────────────

    function test_DC07_AttackerBlockedBySafeDelegate() public {
        // TODO: deploy fixed delegate, verify attacker is blocked
        vm.startPrank(attacker, attacker);
        vm.expectRevert(); // "only EOA owner can call this"
        // ISafeDelegate(victimEOA).transferETH(attacker, "");
        vm.stopPrank();
        assertTrue(true, "TODO: implement");
    }

    function _etch7702(address eoa, address delegate) internal {
        vm.etch(eoa, delegate.code);
    }
}
