// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "forge-std/console.sol";

// AUTO-GENERATED by DelegateGuard harness generator
// Bug class : PA-04 — EOA-only reentrancy path
// Contract  : PA04_EOAReentrancy
// Function  : withdraw
// Source    : src/vulnerable/PA04_PA05_Vulnerable.sol:26

// Reentrant delegate: calls back into protocol on ETH receipt
contract ReentrantDelegate_PA04_PA04_EOAReentrancy_withdraw_Harness {
    address public target;
    uint256 public depth;

    constructor(address _target) { target = _target; }

    receive() external payable {
        if (depth == 0) {
            depth++;
            // Reenter the vulnerable function
            (bool ok,) = target.call(abi.encodeWithSignature("withdraw()"));
            ok;
        }
    }
}

contract PA04_PA04_EOAReentrancy_withdraw_Harness is Test {

    address payable public delegatedEOA;
    address public attacker = makeAddr("attacker");
    ReentrantDelegate_PA04_PA04_EOAReentrancy_withdraw_Harness public reentrantDel;

    function setUp() public {
        delegatedEOA = payable(makeAddr("delegatedEOA"));
        vm.deal(delegatedEOA, 5 ether);

        // TODO: deploy PA04_EOAReentrancy
        // address protocol = address(new PA04_EOAReentrancy());
        // reentrantDel = new ReentrantDelegate_PA04_PA04_EOAReentrancy_withdraw_Harness(protocol);
        // vm.etch(delegatedEOA, address(reentrantDel).code);

        // Seed the protocol with the EOA's deposit
        // vm.store(address(protocol), keccak256(abi.encode(delegatedEOA, 0)), bytes32(uint256(2 ether)));
        // vm.deal(address(protocol), 5 ether);
    }

    // ── RED: delegated EOA reenters via receive() hook ───────────────────────

    function test_PA04_DelegatedEOAReenters() public {
        uint256 balanceBefore = delegatedEOA.balance;
        console.log("Delegated EOA balance before:", balanceBefore);

        vm.prank(delegatedEOA);
        // PA04_EOAReentrancy(protocol).withdraw();

        // INVARIANT: EOA should not be able to withdraw more than deposited
        // assertGt(delegatedEOA.balance, 2 ether, "REENTRANCY: extracted more than deposited");
        assertTrue(true, "TODO: uncomment assertions");
    }

    // ── GREEN: nonReentrant blocks reentrancy ────────────────────────────────

    function test_PA04_NonReentrantBlocksEOAReentrancy() public {
        vm.prank(delegatedEOA);
        vm.expectRevert(); // "reentrant"
        // IFixedProtocol(protocol).withdraw();
        assertTrue(true, "TODO: implement");
    }
}
