import { ScanResult } from "./types";

// Rich mock data — used when the Python CLI is not available (Vercel deploy)
// Mirrors the actual output format from delegateguard analyze/scan
export const MOCK_SCAN: ScanResult = {
  target: "contracts/delegates/",
  mode: "both",
  total: 11,
  duration_ms: 3420,
  timestamp: new Date().toISOString(),
  findings: [
    {
      bug_class: "DC-07",
      severity: "CRITICAL",
      title: "Sweeper pattern — arbitrary call with no allowlist (DC-07)",
      description: "`SweeperDelegate.execute()` issues an arbitrary external call missing: caller authentication, call-target allowlist. An attacker who tricks a user into delegating to this contract can drain all ETH and tokens in one transaction.",
      contract: "SweeperDelegate",
      function: "execute",
      line: 26,
      source_file: "contracts/delegates/SweeperDelegate.sol",
      recommendation: "1. Add `onlyOwner` (require msg.sender == owner). 2. Maintain an explicit `mapping(address => bool) allowedTargets` and check it before every external call.",
      poc_ref: "lab/test/DC07_Sweeper.t.sol",
    },
    {
      bug_class: "DC-05",
      severity: "CRITICAL",
      title: "Unsafe inner DELEGATECALL to unconstrained target (DC-05)",
      description: "`PluginRouter.executePlugin()` issues a DELEGATECALL to `plugin` with no allowlist check. An attacker can pass a malicious contract as the target and execute arbitrary code in the EOA's context.",
      contract: "PluginRouter",
      function: "executePlugin",
      line: 61,
      source_file: "contracts/delegates/PluginRouter.sol",
      recommendation: "Maintain an explicit allowlist of approved DELEGATECALL targets: `mapping(address => bool) allowedPlugins`. Check `require(allowedPlugins[target])` before every delegatecall.",
      poc_ref: "lab/test/DC05_InnerDelegatecall.t.sol",
    },
    {
      bug_class: "DC-03",
      severity: "CRITICAL",
      title: "Missing chain_id in domain separator — cross-chain replay (DC-03)",
      description: "`BatchExecutor` uses EIP-712 signatures but the domain separator does not include `block.chainid`. A signature produced on Ethereum mainnet can be replayed on Arbitrum, Base, Optimism, and any other EVM chain.",
      contract: "BatchExecutor",
      function: null,
      line: 20,
      source_file: "contracts/delegates/BatchExecutor.sol",
      recommendation: "Include `block.chainid` in the EIP-712 domain separator: `keccak256(abi.encode(DOMAIN_TYPEHASH, name, version, block.chainid, address(this)))`.",
      poc_ref: "lab/test/DC03_CrossChainReplay.t.sol",
    },
    {
      bug_class: "DC-04",
      severity: "HIGH",
      title: "Missing per-call authentication (DC-04)",
      description: "`DelegateWallet.transferETH()` is a public/external state-changing function with no msg.sender authentication. Any external caller can invoke it via the delegated EOA.",
      contract: "DelegateWallet",
      function: "transferETH",
      line: 47,
      source_file: "contracts/delegates/DelegateWallet.sol",
      recommendation: "Add an `onlyOwner` modifier or explicit `require(msg.sender == owner, 'not owner')` check to every state-changing function.",
      poc_ref: "lab/test/DC04_MissingAuth.t.sol",
    },
    {
      bug_class: "DC-02",
      severity: "HIGH",
      title: "Unprotected initializer — front-run risk (DC-02)",
      description: "`DelegateWallet.initialize()` has no caller authentication. Any address can call this before the EOA owner does, taking ownership of the delegated account.",
      contract: "DelegateWallet",
      function: "initialize",
      line: 28,
      source_file: "contracts/delegates/DelegateWallet.sol",
      recommendation: "Add `require(msg.sender == tx.origin && tx.origin == address(this), 'only EOA can initialize')` OR bundle initialization atomically with the EIP-7702 authorization.",
      poc_ref: "lab/test/DC02_InitFrontrun.t.sol",
    },
    {
      bug_class: "DC-01",
      severity: "HIGH",
      title: "Storage collision on re-delegation (DC-01)",
      description: "State variable `owner` in `DelegateWallet` uses a raw storage slot. If the EOA switches to another delegate with overlapping slots, storage will be corrupted.",
      contract: "DelegateWallet",
      function: null,
      line: 16,
      source_file: "contracts/delegates/DelegateWallet.sol",
      recommendation: "Use ERC-7201 namespaced storage: declare a struct, compute `slot = keccak256(abi.encode(uint256(keccak256('your.namespace')) - 1)) & ~bytes32(uint256(0xff))`, access via assembly `s.slot := slot`.",
      poc_ref: "lab/test/DC01_StorageCollision.t.sol",
    },
    {
      bug_class: "DC-06",
      severity: "HIGH",
      title: "Batch executor replay / nonce gap (DC-06)",
      description: "`BatchExecutor.executeSignedCall()` is missing: deadline, global nonce (uses per-target nonce). Per-target nonces allow the same signature to be replayed against a different target.",
      contract: "BatchExecutor",
      function: "executeSignedCall",
      line: 64,
      source_file: "contracts/delegates/BatchExecutor.sol",
      recommendation: "Use a single monotonically-incrementing global nonce. Include a `deadline` (uint256) in the signed struct and check `require(block.timestamp <= deadline, 'expired')`.",
      poc_ref: "lab/test/DC06_BatchReplay.t.sol",
    },
    {
      bug_class: "PA-04",
      severity: "CRITICAL",
      title: "EOA-only reentrancy path — bypassable by delegated EOA (PA-04)",
      description: "`LendingPool.withdraw()` sends ETH before updating state (CEI violation) with no universal reentrancy guard. A delegated EOA's receive() hook can reenter this function before balances are zeroed.",
      contract: "LendingPool",
      function: "withdraw",
      line: 112,
      source_file: "contracts/protocol/LendingPool.sol",
      recommendation: "1. Add a universal `nonReentrant` modifier (no EOA carve-out). 2. Follow CEI: update all state variables BEFORE making external calls.",
      poc_ref: "lab/test/PA04_EOAReentrancy.t.sol",
    },
    {
      bug_class: "PA-01",
      severity: "HIGH",
      title: "tx.origin used for authentication (PA-01)",
      description: "`Vault.withdrawAll()` uses `tx.origin` for authentication. A phishing contract can trick the victim into calling it, which then calls the vault — tx.origin still passes but msg.sender is the attacker.",
      contract: "Vault",
      function: "withdrawAll",
      line: 30,
      source_file: "contracts/protocol/Vault.sol",
      recommendation: "Replace `tx.origin` with `msg.sender` for all authentication checks.",
      poc_ref: "lab/test/PA01_TxOrigin.t.sol",
    },
    {
      bug_class: "PA-03",
      severity: "HIGH",
      title: "extcodesize == 0 EOA check broken by EIP-7702 (PA-03)",
      description: "`Airdrop.deposit()` uses `extcodesize` to identify EOAs. Post-EIP-7702, delegated EOAs have a 23-byte code slot and fail this check.",
      contract: "Airdrop",
      function: "deposit",
      line: 96,
      source_file: "contracts/protocol/Airdrop.sol",
      recommendation: "Remove extcodesize-based EOA detection. For reentrancy: use a universal nonReentrant modifier with no EOA carve-out.",
      poc_ref: "lab/test/PA03_ExtcodeSize.t.sol",
    },
    {
      bug_class: "PA-05",
      severity: "MEDIUM",
      title: "EOA = unique human assumption broken by EIP-7702 (PA-05)",
      description: "`Airdrop.claimAirdrop()` gates a one-per-address action using an EOA check. Post-EIP-7702, an attacker can generate a farm of EOAs and claim the action N times.",
      contract: "Airdrop",
      function: "claimAirdrop",
      line: 61,
      source_file: "contracts/protocol/Airdrop.sol",
      recommendation: "Replace EOA-based Sybil resistance with a Merkle-proof allowlist or ZK proof of personhood.",
      poc_ref: "lab/test/PA05_EOAUniqueness.t.sol",
    },
  ],
};